kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: .devcontainer/Dockerfile
    debug: true
  purge: true
  commands:
  - ls -al
  - docker build -f .devcontainer/Dockerfile -t drone-test .
  - docker run -d -name drone-test drone-test
  dry_run: true

- name: build package
  image: drone-test
  purge: true
  commands:
  - dpkg-buildpackage -b

trigger:
  event:
  include:
    - push
  exclude:
    - pull_request