kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/docker
  dockerfile: .devcontainer/Dockerfile
  purge: true
  commands:
  - docker build -t drone-test .
  - docker run drone-test