kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    dockerfile: .devcontainer/Dockerfile
    debug: true
  purge: true
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - sleep 5 # give docker enough time to start
  - docker ps -a
  - docker build -f .devcontainer/Dockerfile -t drone-test .
  - docker run drone-test --name drone-test
  dry_run: true

- name: build package
  image: drone-test
  purge: true
  commands:
  - dpkg-buildpackage -b

trigger:
  event:
  include:
    - push
  exclude:
    - pull_request

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock