kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/docker
  dockerfile: .devcontainer/Dockerfile
  purge: true
  commands:
  - docker build -t drone-test .
  - docker run drone-test
  dry_run: true

- name: build package
  image: drone-test
  commands:
  - dpkg-buildpackage -b

trigger:
  event:
  include:
    - push
  branch:
  - main