kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker:dind
  settings:
    dockerfile: .devcontainer/Dockerfile
    debug: true
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - docker ps -a
  - docker build -f .devcontainer/Dockerfile -t drone-test .
  - docker run -d -name drone-test drone-test
  dry_run: true

- name: build package
  image: drone-test
  commands:
  - dpkg-buildpackage -b

trigger:
  event:
  include:
    - push
  exclude:
    - pull_request