kind: pipeline
type: docker
name: default

steps:
- name: build image
  image: plugins/docker
  settings:
    debug: true
  purge: true
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build -f .devcontainer/Dockerfile -t drone-test .
  - docker run --name drone-test drone-test 
  dry_run: true

- name: build package
  image: drone-test
  purge: true
  privileged: true
  commands:
  - ls -alR
  - dpkg-buildpackage -b
  when:
  status:
  - success

- name: cleanup
  image: plugins/docker
  privileged: true
  failure: ignore
  commands:
  - docker container stop drone-test
  - docker container rm drone-test

# - name: notify
#   image: plugins/slack
#   settings:
#     webhook: https://hooks.slack.com/services/...

trigger:
  event:
  include:
    - push
  exclude:
    - pull_request

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock