kind: pipeline
type: docker
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    debug: true
  purge: true
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build -f .devcontainer/Dockerfile -t drone-test .
  - docker run --name drone-test drone-test 
  dry_run: true

- name: build package
  image: drone-test
  purge: true
  commands:
  - dpkg-buildpackage -b

- name: cleanup
  image: plugins/docker
  commands:
  - docker container stop drone-test
  - docker container rm drone-test

trigger:
  event:
  include:
    - push
  exclude:
    - pull_request

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock