version: '3.6'

services:

  drone:
    container_name: drone
    image: drone/drone:2
    restart: unless-stopped
    environment:
      - DRONE_DATABASE_DRIVER=sqlite3
      - DRONE_DATABASE_DATASOURCE=/data/database.sqlite
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_USER_CREATE=${DRONE_USER_CREATE}
      - DRONE_CLEANUP_INTERVAL=${DRONE_CLEANUP_INTERVAL}
      - DRONE_MAX_PROCS=${DRONE_MAX_PROCS}
      - DRONE_TLS_AUTOCERT=false
      - DRONE_LOGS_DEBUG=false
      - DRONE_LOGS_TEXT=true
      - DRONE_LOGS_COLOR=true
      # - DRONE_TLS_CERT=${DRONE_TLS_CERT}
      # - DRONE_TLS_KEY=${DRONE_TLS_KEY}
    ports:
      - "80:80"
      # - "443:443"
    networks:
      - drone_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./drone:/data

  drone-git:
    container_name: drone-git
    image: alpine/git
    restart: unless-stopped
    depends_on:
      - drone

  drone-runner:
    container_name: drone-runner
    image: drone/drone-runner-docker:1
    restart: unless-stopped
    depends_on:
      - drone
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone:80
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_NAME="${HOSTNAME}-runner"
      - DRONE_RUNNER_CAPACITY=10
      - DRONE_RUNNER_NETWORKS=drone_net
      - DRONE_DEBUG=true
      - DRONE_TRACE=false
    # ports:
    #   - "3000:3000"
    networks:
      - drone_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  drone-gc:
    container_name: drone-gc
    image: drone/gc:latest
    restart: unless-stopped
    environment:
      - GC_DEBUG=true
      - GC_CACHE=5gb
      - GC_INTERVAL=5m
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  drone_net:
    name: drone_net